<a href="https://colab.research.google.com/github/china-srun/Machine-Learning/blob/main/KNN_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
#lib
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
#use KNN algorithm
from sklearn.neighbors import KNeighborsClassifier
#import dataset from sklearn
from sklearn import datasets
#prepocess the dataset
from sklearn.preprocessing import StandardScaler

In [41]:
#upload the dataset from sklearn itself since the iris dataset already exist in sklearn
# iris = datasets.load_iris()

#or import the dataset from local
from google.colab import files
upload = files.upload()

Saving Iris.csv to Iris (1).csv


In [42]:
#read the dataset
iris = pd.read_csv("Iris.csv")
iris.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [43]:
#to see how many rows and columns we have in the dataset
iris.shape

#to see how many columns we have
iris.columns

#to see how many rows or see the rows data we have
# iris.values

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [44]:
#split the attribute into 2 parts (x variable and y variable)
x_variable = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'] #to know the species, we use the info 
y_variable = ['Species'] #we want to analyse its species, in this case, this is the targert variable


#reshape the variable
x = iris[x_variable].values.reshape(-1, len(x_variable)) #1st always -1, the second is the len of x_variable
y = iris[y_variable].values.reshape(-1, len(y_variable))

print(x.shape)
print(y.shape)

(150, 4)
(150, 1)


# Without using StandardScaler, we use basic data preprocessing now

In [45]:
#split the dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1) #train 80%, test 20%, we use random_state in order to have the same value everytime
print(x_train.shape)
print(y_train.shape)

(120, 4)
(120, 1)


In [46]:
#model building
knn_model = KNeighborsClassifier(n_neighbors=5, n_jobs=-1).fit(x_train,  y_train) #default value for n_jobs is -1

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [47]:
#predict whole dataset
y_predict = knn_model.predict(x_test)
print(y_predict)
y_predict.shape

['Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica']


(30,)

In [48]:
#dataframe of predict and actual values
data = {'Actual': y_test.flatten(), 'Predicted': y_predict}
df = pd.DataFrame(data)
print(df)

             Actual        Predicted
0       Iris-setosa      Iris-setosa
1   Iris-versicolor  Iris-versicolor
2   Iris-versicolor  Iris-versicolor
3       Iris-setosa      Iris-setosa
4    Iris-virginica   Iris-virginica
5   Iris-versicolor  Iris-versicolor
6    Iris-virginica   Iris-virginica
7       Iris-setosa      Iris-setosa
8       Iris-setosa      Iris-setosa
9    Iris-virginica   Iris-virginica
10  Iris-versicolor  Iris-versicolor
11      Iris-setosa      Iris-setosa
12   Iris-virginica   Iris-virginica
13  Iris-versicolor  Iris-versicolor
14  Iris-versicolor  Iris-versicolor
15      Iris-setosa      Iris-setosa
16  Iris-versicolor  Iris-versicolor
17  Iris-versicolor  Iris-versicolor
18      Iris-setosa      Iris-setosa
19      Iris-setosa      Iris-setosa
20  Iris-versicolor  Iris-versicolor
21  Iris-versicolor  Iris-versicolor
22  Iris-versicolor  Iris-versicolor
23      Iris-setosa      Iris-setosa
24   Iris-virginica   Iris-virginica
25  Iris-versicolor  Iris-versicolor
2

In [49]:
#to see our predicted value of our x_test
knn_model.predict_proba(x_test)

array([[1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0.8, 0.2],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.6, 0.4],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.4, 0.6]])

0 - Iris setosa
1 - Iris versicolor
2 - Iris virginica
First result explains that 100% is iris setosa, [0, 0.8, 0.2] explains that 80% is iris versicolor and 20% is iris virginica


In [50]:
# to see the probability of success of our predicted value 
# predict one dataset
# the input we put here is completely random
# the 4 input here represents the 4 columns we have
# remember that in order to predict the specices, we need to learn from the data in the 4 columns
input = np.array([3, 4.5, 6, 1])
input = input.reshape(-1, len(x_variable))

y_predict1 = knn_model.predict(input)
print(y_predict1)

['Iris-virginica']


In [51]:
knn_model.predict_proba(input)

# the result shows that 60% of our input data is Iris-virginica

array([[0. , 0.4, 0.6]])

In [52]:
# this is the exact value in which we know the answer to.  we want to check whether our prediction is correct or not

# based on our data in the dataset, we are 100% sure that the specises of our input data is gotta be iris-virginica
# if the asnwer is iris-virginica then, our prediction is correct
input1 = np.array([7.7, 2.6, 6.9, 2.3])
input1 = input1.reshape(-1, len(x_variable))

y_predict2 = knn_model.predict(input1)
print(y_predict2)

knn_model.predict_proba(input1)
# 100% sure that it is iris-virginica

['Iris-virginica']


array([[0., 0., 1.]])

In [53]:
# to see how accurate we are based on our prediction (accuracy score)
from sklearn.metrics import accuracy_score
accuracy_result = accuracy_score(y_test, y_predict)
print(accuracy_result)
# so based on the answer, we are 100% correct with our prediction

1.0


Process:
1.   Library
2.   Dataset
3.   Preprocessing
    3.1. x_variable, y_variable
    3.2. reshape
4.   Model building
5.   Predict the result(whole dataset, single_value)
6.   Probability of success
7. Evaluation metrics (accuracy) - accuracy score(only work for whole dataset, single data will throw an error)


Homework: 
1. Create a table between actual and predict
2. Check the formula of accuracy score. 
3. Find the procedure to get the optimal k-value (how to find k-value)


In [54]:
# 1. create a table between actual and predict data
data = {'Actual': y_test.flatten(), 'Predicted': y_predict}
df = pd.DataFrame(data)
print(df)

             Actual        Predicted
0       Iris-setosa      Iris-setosa
1   Iris-versicolor  Iris-versicolor
2   Iris-versicolor  Iris-versicolor
3       Iris-setosa      Iris-setosa
4    Iris-virginica   Iris-virginica
5   Iris-versicolor  Iris-versicolor
6    Iris-virginica   Iris-virginica
7       Iris-setosa      Iris-setosa
8       Iris-setosa      Iris-setosa
9    Iris-virginica   Iris-virginica
10  Iris-versicolor  Iris-versicolor
11      Iris-setosa      Iris-setosa
12   Iris-virginica   Iris-virginica
13  Iris-versicolor  Iris-versicolor
14  Iris-versicolor  Iris-versicolor
15      Iris-setosa      Iris-setosa
16  Iris-versicolor  Iris-versicolor
17  Iris-versicolor  Iris-versicolor
18      Iris-setosa      Iris-setosa
19      Iris-setosa      Iris-setosa
20  Iris-versicolor  Iris-versicolor
21  Iris-versicolor  Iris-versicolor
22  Iris-versicolor  Iris-versicolor
23      Iris-setosa      Iris-setosa
24   Iris-virginica   Iris-virginica
25  Iris-versicolor  Iris-versicolor
2

Answer:
2. We calculate accuracy score based on a formula: accuracy_score = number of correct predictions / total number of predictions.
3. Based on my reserach, there is no simple formula for calculating K. To find the best k-value , we should try out different value. However, these are the basic value people usually choose for k-value:
  - let k = sqrt(n) where n is number of data in training data
  - try random number but should be an odd number
  - value should not be too large or too small

In [ ]:
# preprocessing
    # StandardScaler process is used to resize the distribution of values ​​so that the mean of the observed values ​​is 0 and the standard deviation is 1.
    # StandardScaler: choose one common unit to do the process
    # Data preprocessing in Machine Learning refers to the technique of preparing (cleaning and organizing) the raw data to make it suitable for a building and training Machine Learning models.

standardizer = StandardScaler()